# Site settings
name: "Europivot Limited"
description: ""
baseurl: "/"
url: "http://www.europivot.co.uk"

# Build settings
markdown: rdiscount
permalink: pretty

sass:
 sass_dir: _sass
 style: :compressed
