# Site settings
name: "Europivot Limited"
description: "Europivot Limited - Property development specialists"


# Build settings
markdown: rdiscount
permalink: pretty

sass:
 sass_dir: _sass
 style: :compressed
