#---------------------------------------------
# Menu Items

menu:
- {name: 'Projects', url: '/'}
- {name: 'About Us', url: '/about-us/'}
- {name: 'Contact', url: '/contact/'}

#---------------------------------------------
# Projects

projects:
- {name: 'Agar Grove, Camden, London',
  url: /projects/agar-grove/,
  large: /images/projects/agar-grove/agar-grove-L.jpg,
  medium: /images/projects/agar-grove/agar-grove-M.jpg,
  small: /images/projects/agar-grove/agar-grove-S.jpg}
- {name: 'Arepa & Co, Haggerston, London',
  url: /projects/arepa-co/,
  large: /images/projects/arepa-co/arepa-co-L.jpg,
  medium: /images/projects/arepa-co/arepa-co-M.jpg,
  small: /images/projects/arepa-co/arepa-co-S.jpg}
- {name: 'Baxendale Street, Tower Hanlet, London',
  url: /projects/baxendale-street/,
  large: /images/projects/baxendale/baxendale-L.jpg,
  medium: /images/projects/baxendale/baxendale-M.jpg,
  small: /images/projects/baxendale/baxendale-S.jpg}
  
images:
- {name: 'Agar', total: 3}
- {name: 'Arepa', total: 5}
- {name: 'Baxendale', total: 4}